# Generated by Django 5.2.5 on 2025-09-08 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voice_flow', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='guardian_contact',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='guardian_name',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='guardian_relationship',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='school_grade',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='vaccination_status',
        ),
    ]
